### ISSUE TITLE
[Bug]: Wrong voltage value in oscilloscope view

### ISSUE THREAD

**Issue by med-anis-bm** [jetperch/pyjoulescope_ui#175] opened 2022-11-15 15:10 UTC
### UI version

0.10.12

### What OS are you seeing the problem on?

Windows 10

### What happened?

I'm using the JS220 with the latest UI version **0.10.12**.
In oscilloscope mode, the voltage value is always 2.2V knowing that i i'm injecting 3V. I verified with an external voltmeter and the voltage in input and output of the joulescope is 3V.
![image](https://user-images.githubusercontent.com/118286433/201953205-e109f862-b00b-4fe1-b406-fac84a159056.png)

When switching to multimeter view, the UI displays the correct voltage.
![image](https://user-images.githubusercontent.com/118286433/201953295-5fdb53ea-ff62-4346-b7a2-949122738587.png)

### What was expected?

Oscilloscope should display the correct voltage

### How to reproduce?

1. ...Select oscilloscope view
2. ...Check the voltage value
3. ...

**Comment by mliberty1** [comment] 2022-11-15 15:19
Hi @med-anis-bm - Did you select the fixed 2V range?  Like this:

![image](https://user-images.githubusercontent.com/5393422/201956409-1a6762e8-58fb-4f52-85db-0a960e284357.png)

Note that the Multimeter View and Oscilloscope View have their own defaults and will switch this setting.

**Comment by med-anis-bm** [comment] 2022-11-15 15:37
Hi, No im selecting 15V range 
![image](https://user-images.githubusercontent.com/118286433/201960969-50efb1ef-890f-451a-bd4f-82e7c9eb0150.png)

**Comment by mliberty1** [comment] 2022-11-15 15:46
It looks like you have stopped streaming.  Could you start streaming?  Is it then correct?

If you still see the issue, could you try toggling to 2V then back to 15V?  Any difference in the reading?

**Comment by med-anis-bm** [comment] 2022-11-15 16:04
Switching to 2V and then going back to 15V resolved the issue, Thank you

**Comment by mliberty1** [comment] 2022-11-15 16:14
Great!  I tried playing around, and I think that I figured out how you arrived at this issue, which is actually a bug.  The issue is switching from the JS110 to the JS220.  Here is how to duplicate:

1, Connect both a JS110 and a JS220 to the same host computer and start the UI,
2. Select a JS110
3. Set **Voltage Range** => **5V**
4. Select a JS220
5. The **Voltage Range** now shows 15V (since 5V is not valid), but the UI still sets the JS220 for the more sensitive 2V range.
6. Select **2V** then **15V** fixes.

**Comment by med-anis-bm** [comment] 2022-11-15 16:19
> Great! I tried playing around, and I think that I figured out how you arrived at this issue, which is actually a bug. The issue is switching from the JS110 to the JS220. Here is how to duplicate:
> 
> 1. Connect both a JS110 and a JS220 to the same host computer and start the UI.
> 2. Select a JS110.
> 3. Set **Voltage Range** => **5V**.
> 4. Select a JS220.
> 5. The **Voltage Range** now shows 15V (since 5V is not valid), but the UI still sets the JS220 for the more sensitive 2V range.
> 6. Select **2V** then **15V** fixes.

I confirm, That was exactly the case

**Comment by mliberty1** [comment] 2023-03-10 19:15
Fixed by 1.0.0 which has separate settings for JS110's and JS220's.

**Closed by mliberty1** 2023-03-10 19:15 UTC
Labels: bug
